"""add ml training samples

Revision ID: 0bd99598430a
Revises: 3810e605936e
Create Date: 2026-09-02 10:52:43.299561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd99598430a'
down_revision: Union[str, Sequence[str], None] = '3810e605936e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_training_samples',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('query_id', sa.BigInteger(), nullable=False),
    sa.Column('recommendation_id', sa.BigInteger(), nullable=True),
    sa.Column('total_calls', sa.BigInteger(), nullable=False),
    sa.Column('latency_sample_count', sa.Integer(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('min_latency_ms', sa.Float(), nullable=True),
    sa.Column('max_latency_ms', sa.Float(), nullable=True),
    sa.Column('p95_latency_ms', sa.Float(), nullable=True),
    sa.Column('plan_total_cost', sa.Float(), nullable=True),
    sa.Column('plan_rows', sa.Float(), nullable=True),
    sa.Column('filter_column_count', sa.Integer(), nullable=False),
    sa.Column('index_column_count', sa.Integer(), nullable=False),
    sa.Column('benchmark_before_ms', sa.Float(), nullable=True),
    sa.Column('benchmark_after_ms', sa.Float(), nullable=True),
    sa.Column('improvement_percent', sa.Float(), nullable=True),
    sa.Column('benchmark_stability', sa.Float(), nullable=True),
    sa.Column('historical_success_rate', sa.Float(), nullable=True),
    sa.Column('historical_avg_improvement', sa.Float(), nullable=True),
    sa.Column('historical_avg_confidence', sa.Float(), nullable=True),
    sa.Column('decision_confidence', sa.Float(), nullable=True),
    sa.Column('decision_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_training_samples_query_id'), 'ml_training_samples', ['query_id'], unique=False)
    op.create_index(op.f('ix_ml_training_samples_recommendation_id'), 'ml_training_samples', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_training_samples_recommendation_id'), table_name='ml_training_samples')
    op.drop_index(op.f('ix_ml_training_samples_query_id'), table_name='ml_training_samples')
    op.drop_table('ml_training_samples')
    # ### end Alembic commands ###
