"""add ml training samples v2

Revision ID: 1b77fc24d97c
Revises: 7500cefbdb4e
Create Date: 2026-09-02 14:50:04.694183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b77fc24d97c'
down_revision: Union[str, Sequence[str], None] = '7500cefbdb4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_training_samples_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.BigInteger(), nullable=False),
    sa.Column('recommendation_id', sa.BigInteger(), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=True),
    sa.Column('latency_sample_count', sa.Integer(), nullable=True),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('min_latency_ms', sa.Float(), nullable=True),
    sa.Column('max_latency_ms', sa.Float(), nullable=True),
    sa.Column('p95_latency_ms', sa.Float(), nullable=True),
    sa.Column('plan_total_cost', sa.Float(), nullable=True),
    sa.Column('plan_rows', sa.Float(), nullable=True),
    sa.Column('seq_scan_count', sa.Integer(), nullable=True),
    sa.Column('actual_rows', sa.Float(), nullable=True),
    sa.Column('rows_removed_by_filter', sa.Float(), nullable=True),
    sa.Column('actual_total_time_ms', sa.Float(), nullable=True),
    sa.Column('actual_loops', sa.Float(), nullable=True),
    sa.Column('scan_selectivity_ratio', sa.Float(), nullable=True),
    sa.Column('removed_to_returned_ratio', sa.Float(), nullable=True),
    sa.Column('equality_filter_count', sa.Integer(), nullable=True),
    sa.Column('range_filter_count', sa.Integer(), nullable=True),
    sa.Column('like_filter_count', sa.Integer(), nullable=True),
    sa.Column('has_order_by', sa.Integer(), nullable=True),
    sa.Column('has_limit', sa.Integer(), nullable=True),
    sa.Column('candidate_column_count', sa.Integer(), nullable=True),
    sa.Column('candidate_has_order_column', sa.Integer(), nullable=True),
    sa.Column('source_actual_rows', sa.Float(), nullable=True),
    sa.Column('source_rows_removed_by_filter', sa.Float(), nullable=True),
    sa.Column('historical_success_rate', sa.Float(), nullable=True),
    sa.Column('historical_avg_improvement', sa.Float(), nullable=True),
    sa.Column('benchmark_before_ms', sa.Float(), nullable=True),
    sa.Column('benchmark_after_ms', sa.Float(), nullable=True),
    sa.Column('improvement_percent', sa.Float(), nullable=True),
    sa.Column('benchmark_stability', sa.Float(), nullable=True),
    sa.Column('decision_confidence', sa.Float(), nullable=True),
    sa.Column('decision_status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_training_samples_v2_id'), 'ml_training_samples_v2', ['id'], unique=False)
    op.create_index(op.f('ix_ml_training_samples_v2_query_id'), 'ml_training_samples_v2', ['query_id'], unique=False)
    op.create_index(op.f('ix_ml_training_samples_v2_recommendation_id'), 'ml_training_samples_v2', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_training_samples_v2_recommendation_id'), table_name='ml_training_samples_v2')
    op.drop_index(op.f('ix_ml_training_samples_v2_query_id'), table_name='ml_training_samples_v2')
    op.drop_index(op.f('ix_ml_training_samples_v2_id'), table_name='ml_training_samples_v2')
    op.drop_table('ml_training_samples_v2')
    # ### end Alembic commands ###
