"""add missing query latency stats

Revision ID: 3810e605936e
Revises: 5969406b3b79
Create Date: 2026-09-02 09:31:42.686287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3810e605936e'
down_revision: Union[str, Sequence[str], None] = '5969406b3b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('max_latency_ms', sa.Float(), nullable=True))
    op.add_column('queries', sa.Column('p95_latency_ms', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'p95_latency_ms')
    op.drop_column('queries', 'max_latency_ms')
    # ### end Alembic commands ###
