"""add query execution samples and latency stats

Revision ID: 5969406b3b79
Revises: 5c89fba9b753
Create Date: 2026-09-02 08:47:25.359375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5969406b3b79'
down_revision: Union[str, Sequence[str], None] = '5c89fba9b753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_execution_samples',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('query_id', sa.BigInteger(), nullable=False),
    sa.Column('execution_time_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_execution_samples_query_id'), 'query_execution_samples', ['query_id'], unique=False)
    op.add_column('queries', sa.Column('min_latency_ms', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'min_latency_ms')
    op.drop_index(op.f('ix_query_execution_samples_query_id'), table_name='query_execution_samples')
    op.drop_table('query_execution_samples')
    # ### end Alembic commands ###
