"""create initial tables

Revision ID: 7a3c08f01ef2
Revises: 
Create Date: 2026-08-31 11:47:07.202373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a3c08f01ef2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_connections_id'), 'database_connections', ['id'], unique=False)
    op.create_table('queries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('normalized_query', sa.Text(), nullable=False),
    sa.Column('total_calls', sa.BigInteger(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['database_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queries_database_id'), 'queries', ['database_id'], unique=False)
    op.create_index(op.f('ix_queries_query_hash'), 'queries', ['query_hash'], unique=False)
    op.create_table('query_plans',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('query_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_json', sa.JSON(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('plan_rows', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_plans_query_id'), 'query_plans', ['query_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('query_id', sa.BigInteger(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('sql_command', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_query_id'), 'recommendations', ['query_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_query_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_query_plans_query_id'), table_name='query_plans')
    op.drop_table('query_plans')
    op.drop_index(op.f('ix_queries_query_hash'), table_name='queries')
    op.drop_index(op.f('ix_queries_database_id'), table_name='queries')
    op.drop_table('queries')
    op.drop_index(op.f('ix_database_connections_id'), table_name='database_connections')
    op.drop_table('database_connections')
    # ### end Alembic commands ###
