"""add database password

Revision ID: afb981445475
Revises: 7a3c08f01ef2
Create Date: 2026-08-31 13:22:41.120863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afb981445475'
down_revision: Union[str, Sequence[str], None] = '7a3c08f01ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "database_connections",
        sa.Column(
            "password",
            sa.String(length=255),
            nullable=True,
        ),
    )

    op.execute(
        """
        UPDATE database_connections
        SET password = 'temporary_password'
        WHERE password IS NULL
        """
    )

    op.alter_column(
        "database_connections",
        "password",
        nullable=False,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('database_connections', 'password')
    # ### end Alembic commands ###
